
package com.alma.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckCreditCardService", targetNamespace = "http://webservices.alma.org", wsdlLocation = "http://localhost:8080/SOAPService/services/CheckCreditCard?wsdl")
public class CheckCreditCardService
    extends Service
{

    private final static URL CHECKCREDITCARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKCREDITCARDSERVICE_EXCEPTION;
    private final static QName CHECKCREDITCARDSERVICE_QNAME = new QName("http://webservices.alma.org", "CheckCreditCardService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAPService/services/CheckCreditCard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKCREDITCARDSERVICE_WSDL_LOCATION = url;
        CHECKCREDITCARDSERVICE_EXCEPTION = e;
    }

    public CheckCreditCardService() {
        super(__getWsdlLocation(), CHECKCREDITCARDSERVICE_QNAME);
    }

    public CheckCreditCardService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKCREDITCARDSERVICE_QNAME, features);
    }

    public CheckCreditCardService(URL wsdlLocation) {
        super(wsdlLocation, CHECKCREDITCARDSERVICE_QNAME);
    }

    public CheckCreditCardService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKCREDITCARDSERVICE_QNAME, features);
    }

    public CheckCreditCardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckCreditCardService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckCreditCard
     */
    @WebEndpoint(name = "CheckCreditCard")
    public CheckCreditCard getCheckCreditCard() {
        return super.getPort(new QName("http://webservices.alma.org", "CheckCreditCard"), CheckCreditCard.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckCreditCard
     */
    @WebEndpoint(name = "CheckCreditCard")
    public CheckCreditCard getCheckCreditCard(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.alma.org", "CheckCreditCard"), CheckCreditCard.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKCREDITCARDSERVICE_EXCEPTION!= null) {
            throw CHECKCREDITCARDSERVICE_EXCEPTION;
        }
        return CHECKCREDITCARDSERVICE_WSDL_LOCATION;
    }

}
